#!/bin/bash

# 1. Define paths
PROJECT_DIR="/home/arpit/workspace/project_greenscreen"
# Path to the specific Conda environment 'project_gs' python executable
# This bypasses the need to 'activate' the shell, which is often buggy in cron jobs.
PYTHON_EXEC="/home/arpit/anaconda3/envs/project_gs/bin/python3"

echo "--- Starting Daily DSA Task: $(date) ---"

# 2. Navigate to project directory
cd $PROJECT_DIR || { echo "Directory not found"; exit 1; }

# 3. Environment Check
# We don't strictly need to 'source activate' if we point directly to the binary.
echo "Using Python: $PYTHON_EXEC"

# 4. Run the Main Orchestrator
echo "Running main.py..."
$PYTHON_EXEC main.py

# 5. Git Operations
echo "Pushing changes to GitHub..."

# Add specifically the files generated by the agents
git add solution.py question.txt questions.db

# Commit with a timestamp
git commit -m "Daily DSA: $(date +'%Y-%m-%d %H:%M')"

# Push to the main branch
git push origin main

echo "--- Task Completed Successfully ---"